[package]
name = "mochiclaw-plugin"
version.workspace = true
edition.workspace = true
description = "Mochiclaw Plugin - Plugin host, manifest, and registry"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
rmp-serde = "1"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
toml.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json", "blocking"] }
url.workspace = true
glob.workspace = true
extism = { version = "1", default-features = false, features = ["register-filesystem", "wasmtime-default-features"] }
extism-convert = { version = "1", features = ["msgpack"] }
mochiclaw-sdk = { path = "../mochiclaw-sdk" }
mochiclaw-config = { path = "../mochiclaw-config" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
