[package]
name = "mochiclaw-sdk"
version.workspace = true
edition.workspace = true
description = "Mochiclaw SDK - Shared types for host and lambdas"

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true
extism-pdk.workspace = true
extism-convert.workspace = true
thiserror.workspace = true
