[package]
name = "mochi-openai"
version.workspace = true
edition.workspace = true
description = "OpenAI-compatible provider lambda for Mochiclaw"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
rmp-serde.workspace = true
mochiclaw-sdk = { path = "../../sdk" }
mochiclaw-macro = { path = "../../sdk-macro" }
